version: '3.8'

services:
  django:
    build:
      context: .
    volumes:
      - .:/code
    command: python /code/HospitalSite/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
