# Generated by Django 4.2.7 on 2023-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=255)),
                ("lname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=13)),
                ("specialty", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=1000)),
            ],
        ),
    ]
