# Generated by Django 4.2.7 on 2023-12-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0002_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=150)),
                ("lname", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=13, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("specialty", models.CharField(blank=True, max_length=100, null=True)),
                ("role", models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
