# Generated by Django 4.2.7 on 2023-12-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0004_customuser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_anonymous",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_authenticated",
            field=models.BooleanField(null=True),
        ),
    ]
