# Generated by Django 4.2.7 on 2023-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0005_customuser_is_anonymous_customuser_is_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
    ]
