# Generated by Django 4.2.7 on 2023-12-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0006_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(null=True),
        ),
    ]
