# Generated by Django 4.2.7 on 2024-01-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projectapp",
            "0010_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=13)),
                ("doctor", models.CharField(max_length=255)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
            ],
        ),
    ]
