# Generated by Django 4.2.7 on 2024-01-16 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0011_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="phone",
        ),
    ]
