# Generated by Django 4.2.7 on 2024-01-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0012_remove_appointment_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to="projectapp.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to="projectapp.customuser",
            ),
        ),
    ]
