# Generated by Django 4.2.7 on 2024-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0013_appointment_patient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
