# Generated by Django 4.2.7 on 2024-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0015_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
