# Generated by Django 4.2.7 on 2024-01-17 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0016_appointment_details_appointment_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="name",
        ),
    ]
