# Generated by Django 4.2.7 on 2024-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0017_remove_appointment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Одобрен", "approved"),
                    ("Преглежда се", "pending"),
                    ("Отказано", "rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
