# Generated by Django 4.2.7 on 2024-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0018_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Одобрен", "approved"),
                    ("Преглежда се", "pending"),
                    ("Отказано", "rejected"),
                ],
                default="Преглежда се",
                max_length=20,
                null=True,
            ),
        ),
    ]
