# Generated by Django 4.2.7 on 2024-02-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0019_alter_appointment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="forgot_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="not set",
                max_length=6,
                null=True,
            ),
        ),
    ]
