# Generated by Django 4.2.7 on 2024-02-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0020_code_customuser_forgot_password_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
