# Generated by Django 4.2.7 on 2024-02-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0021_code_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="room_num",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
