# Generated by Django 4.2.7 on 2024-02-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0022_customuser_room_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="room_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
