# Generated by Django 4.2.7 on 2024-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0023_alter_customuser_room_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Одобрен", "Одобрен"),
                    ("Преглежда се", "Преглежда се"),
                    ("Отказано", "Отказано"),
                ],
                default="Преглежда се",
                max_length=20,
                null=True,
            ),
        ),
    ]
