# Generated by Django 4.2.7 on 2024-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0027_alter_appointment_appointment_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="static/images/")),
            ],
        ),
    ]
