# Generated by Django 4.2.7 on 2024-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0027_alter_appointment_appointment_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="News_page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("author", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
