# Generated by Django 4.2.7 on 2024-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0028_pharmacyitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacyitem",
            name="image",
            field=models.ImageField(upload_to="HospitalSite/static/images/"),
        ),
    ]
