# Generated by Django 4.2.7 on 2024-03-12 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0028_news_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news_page",
            old_name="description",
            new_name="content",
        ),
    ]
