# Generated by Django 4.2.7 on 2024-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0029_rename_description_news_page_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="forgot_password_token",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
