# Generated by Django 4.2.7 on 2024-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0029_alter_pharmacyitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacyitem",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
