# Generated by Django 4.2.7 on 2024-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0030_alter_pharmacyitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="images/")),
                ("author", models.CharField(max_length=50)),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="PharmacyItem",
        ),
    ]
