# Generated by Django 4.2.7 on 2024-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0030_remove_customuser_forgot_password_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
