# Generated by Django 4.2.7 on 2024-02-27 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0031_news_delete_pharmacyitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="News_page",
        ),
    ]
