# Generated by Django 4.2.7 on 2024-02-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0032_rename_news_news_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_page",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
