# Generated by Django 4.2.7 on 2024-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0034_alter_news_page_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_page",
            name="heading",
            field=models.CharField(max_length=255),
        ),
    ]
