# Generated by Django 4.2.7 on 2024-02-27 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0035_alter_news_page_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news_page",
            name="price",
        ),
    ]
