# Generated by Django 4.2.7 on 2024-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectapp", "0036_remove_news_page_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="news_page",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
